# Generated by Django 4.0.5 on 2022-07-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО ответственного')),
                ('org_email', models.EmailField(max_length=255, verbose_name='Эл. почта')),
                ('org_employees', models.CharField(max_length=255, verbose_name='ФИО ответственного')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Время отправки формы')),
            ],
            options={
                'verbose_name': 'Заявка партнера',
                'verbose_name_plural': 'Заявки партнеров',
            },
        ),
    ]
