# Generated by Django 4.0.5 on 2022-07-19 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_partner_org_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок карточки')),
                ('desc', models.TextField(verbose_name='Описание карточки')),
                ('image', models.ImageField(upload_to='cards/')),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер ответственного лица'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержимое статьи')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.card')),
            ],
        ),
    ]
