# Generated by Django 4.0.5 on 2022-07-19 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_card_partner_phone_number_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карточка статей', 'verbose_name_plural': 'Карточки статей'},
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок статьи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.CharField(blank=True, max_length=255, verbose_name='Опциональная ссылка на страницу'),
        ),
        migrations.AlterField(
            model_name='article',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.card', verbose_name='Карточка статьи'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='cards/', verbose_name='Иконка карточки'),
        ),
    ]
