# Generated by Django 4.0.5 on 2022-07-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_article_options_alter_card_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Параграф')),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок блока')),
                ('image', models.ImageField(upload_to='blocks/', verbose_name='Картинка блока статьи')),
                ('lines', models.ManyToManyField(to='api.textline', verbose_name='Параграфы')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='blocks',
            field=models.ManyToManyField(to='api.textblock', verbose_name='Блоки статьи'),
        ),
    ]
