# Generated by Django 4.0.5 on 2022-07-20 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_textline_textblock_article_blocks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textblock',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterModelOptions(
            name='textline',
            options={'verbose_name': 'Параграф', 'verbose_name_plural': 'Параграфы'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
