# Generated by Django 4.0.5 on 2022-07-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_textblock_options_alter_textline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textblock',
            name='image',
            field=models.ImageField(blank=True, upload_to='blocks/', verbose_name='Картинка блока статьи'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок блока'),
        ),
    ]
