version: "3.9"
   
services:
  postgres:
    image: postgres:12
    env_file:
      - './infrastucture/services/postgres/.env'
  django:
    build: ./backend
    command: "gunicorn backend.wsgi --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app/api
      - static_volume:/static
    env_file:
      - './infrastucture/services/postgres/.env'
      - './infrastucture/apps/backend/.env'
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  nginx:
    build:
      context: .
      dockerfile: ./nginx/dockerfile
    volumes:
      - static_volume:/static
    ports:
      - 1337:80
    depends_on: 
      - django
  # frontend:
  #   build: ./frontend
  #   command: "npm run start"
  #   volumes:
  #     - ./frontend:/app/frontend
  #     - node-modules:/app/frontend/node_modules
  #   ports:
  #     - "3000:3000"

volumes:
  node-modules:
  static_volume: