# The first stage
# Build React static files
FROM node as build

WORKDIR /app/frontend
COPY package.json /app/frontend
COPY package-lock.json /app/frontend
RUN npm install
COPY ./ /app/frontend
RUN npm run build

# The second stage
# Copy React static files and start nginx
FROM nginx:1.22-alpine

COPY --from=build /app/frontend/build/ /usr/share/nginx/html


RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d